name: Build and Push a Container Image to Docker Hub

on:
  workflow_dispatch:
  push:
   branches:
    - main

jobs:
  
   build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: action/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{Secret.DOCKER_USERNAME}}
          password: ${{Secret.DOCKER_PASSWORD}}
          
        -name: Build push container
          run: |
          
          
          docker build -t mycontainer:v1 .
          docker tag mycontainer:v1 docker.io/${{secret.DOCKER_USERNAME }}/mycontainer:v1
          docker push docker.io/${{secret.DOCKER_USERNAME }}/mycontainer:v1
        
      
